version: "3"
services:
    frontend:
        container_name: awesome_web
        build:
            context: ./client
            dockerfile: Dockerfile
        image: awesome_web
        ports:
            - '3000:3000'
        stdin_open: true
    backend:
        container_name: awesome_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: awesome_server
        ports:
            - "8000:8000"